<?php
// phpLiteAdmin configuration for IsotoneStack
// Generated by Configure-IsotoneStack.ps1

// Password for phpLiteAdmin (default: admin)
// IMPORTANT: Change this password for security!
$password = 'admin';

// Directory where SQLite databases are stored
$directory = 'C:/isotone/sqlite';

// Theme (options: Default, AlternateBlue, Modern, etc.)
// Use the path to the theme CSS file
$theme = 'modern.css';

// Language
$language = 'en';

// Number of rows to display by default
$rowsNum = 30;

// Maximum file size for imports (in bytes)
$maxSavedChars = 100000;

// Enable debugging
$debug = false;

// Custom functions
$custom_functions = array(
    'md5', 'sha1', 'sha256', 
    'strtoupper', 'strtolower', 
    'ucfirst', 'lcfirst'
);

// Supported SQLite extensions
$allowed_extensions = array('db', 'db3', 'sqlite', 'sqlite3');
?>
